CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'user',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS module_maintenance (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  module_slug VARCHAR(80) NOT NULL UNIQUE,
  is_maintenance INTEGER NOT NULL DEFAULT 0,
  message TEXT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
